services:
  postgres:
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=URLShortener'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=mypass@08'
    ports:
      - '5432:5432'