spring.application.name=URL Shortener
app.base-url=http://localhost:8080
app.default-expiry-in-days=30
app.validate-original-url=true
app.page-size=10

spring.docker.compose.lifecycle-management=start_only
spring.datasource.url=jdbc:postgresql://localhost:5432/URLShortener
spring.datasource.username=postgres
spring.datasource.password=mypass@08
spring.jpa.show-sql=true
spring.jpa.open-in-view=false